server:
  port: 8083
  file:
    upload: C:\\UploadFile\\

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      #swagger config
      matching-strategy: ant_path_matcher
  #db
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: root
      password: roots
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 10000
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
    url: jdbc:mariadb://localhost:3309/coffies?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    #Thyemleaf
    thymeleaf:
      cache: false
      check-template-location: true
      mode: HTML
      prefix: file:src/main/resources/templates/
      suffix: .html
      encoding: UTF-8
      servlet:
        content-type: text/html
  #redis
  redis:
    port: 6379
    host: localhost
  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
